version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: observatory_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: observatory
      POSTGRES_USER: observatory_user
      POSTGRES_PASSWORD: observatory_pass

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01_schema.sql

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U observatory_user" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
